### PR TITLE
Distributed Trainer

### PR DESCRIPTION
**Pull request by PatWie**
Distributed means several training processes (even accross multiple machines).

Not sure if this is possible without rewriting large portions of your code. At least it is an attempt for #144. I mostly focus on transforming the [MWE](https://gist.github.com/PatWie/89950d3f8491a9f0d84125dca0945afa) into a trainer-class.

There are still several things to do:

- [x] Where to place the  SyncReplicasOptimizer? ModelDesc?
- [ ] a `prepare_or_wait_for_session` sessinit class.
- [x] Where does the data comes from? ZeroMQ? Currently, it is multiple processes for each worker.
- [x] I though there was a global_step tensor function, which seems to be required in `tf.train.Supervisor`

I currently just try to use the SyncMultiGPUTrainer before make it more complex. I cannot estimate how complex this feature will be. 
@ppwwyyxx you probably know if the distributed session management currently fits sessinit.py and sesscreate.py. This is the part I never read :wink:

### CODE REVIEW

**Comment by ahundt** [comment]
Coult it be worth considering providing the clusterspec as a parameter?

This is because depending on the distributed system the most sensible manner to initialize the clusterspec will vary, as mentioned in https://github.com/ppwwyyxx/tensorpack/issues/193

**Comment by PatWie** [comment]
As far as I know, it is currently not possible to specify the GPUs for each worker. That's why I used a dict instead.

My current version (I haven't pushed yet) just creates a ClusterTrainer relying on clusterSpec and uses all getting all GPU from CUDA_VISIBLE_DEVICES like the default behavior of TF. But the code is currently not complete. I will post any updates this week if I have time to code.

**Comment by PatWie** [comment]
Now, 
a few updates and findings on this:

- the global_step tensor has to be placed on a [specific device](https://github.com/tensorflow/tensorflow/blob/17c47804b86e340203d451125a721310033710f1/tensorflow/python/training/supervisor.py#L879-L883)
- sometimes TF needs the `global_step` op in the optimizer call. It is required to prevent a stale optimizer.
- there is an complex interplay between the MonitoredSession and the `tf.train.Supervisor` and I am not willing to re-implement most parts of the `Supervisor` class.
- it requires a lot of additional changes in terms of *where* to log and *when* to log or when to write a summary. It seems that the `tf.train.Supervisor` handles this by [knowing whether](https://github.com/tensorflow/tensorflow/blob/17c47804b86e340203d451125a721310033710f1/tensorflow/python/training/supervisor.py#L657-L667) the worker is a chief-worker or not.

For the current version I set the correct ip addresses in:
```python
MACHINE_Q = 'xxx.x.xx.xxx'  # noqa
MACHINE_G = 'xxx.x.xx.xxx'  # noqa
```

and then fire up the example by
```
python mnist-distributed.py --task_id 0 --job ps --gpu 0 # on MACHINE_Q
python mnist-distributed.py --task_id 0 --job worker --gpu 0 # on MACHINE_Q
python mnist-distributed.py --task_id 1 --job worker --gpu 0 # on MACHINE_G
```

The graph is building fine on all machines.  Though I currently get an issue with the [monitored session](https://github.com/tensorflow/tensorflow/blob/52dcb2590bb9274262656c958c105cb5e5cc1300/tensorflow/python/training/monitored_session.py#L428).
```
AttributeError: 'DistributedTrainer' object has no attribute '_monitored_sess'
2017-04-20 11:04:53.496895: E tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:647] failed to record completion event; therefore, failed to create inter-stream dependency
2017-04-20 11:04:53.496958: I tensorflow/stream_executor/stream.cc:4125] stream 0x5c544a0 did not memcpy device-to-host; source: 0x330a3c0800
2017-04-20 11:04:53.496972: E tensorflow/stream_executor/stream.cc:289] Error recording event in stream: error recording CUDA event on stream 0x5c54570: CUDA_ERROR_DEINITIALIZED; not marking stream as bad, as the Event object may be at fault. Monitor for further errors.
2017-04-20 11:04:53.496989: E tensorflow/stream_executor/cuda/cuda_event.cc:49] Error polling for event status: failed to query event: CUDA_ERROR_DEINITIALIZED
2017-04-20 11:04:53.497000: F tensorflow/core/common_runtime/gpu/gpu_event_mgr.cc:203] Unexpected Event status: 1
Aborted
```

It seems that the `sessioncreate.py` in this repo already should distinguish between chief-workers and non-chief-workers. The relevant reference is in https://github.com/tensorflow/tensorflow/blob/52dcb2590bb9274262656c958c105cb5e5cc1300/tensorflow/python/training/monitored_session.py#L343

I

**Comment by PatWie** [comment]
I messed up the last commit and will rebase again.

**Comment by ppwwyyxx** [comment]
Thanks very much for trying out! I'll play with your code soon.

**Comment by PatWie** [comment]
Their tutorial describes a distributed **async** training. But this pull request deals with a **sync** training procedure, which I found more intuitively and less hacky. I have no experience which version is faster (async/sync) or better. But I guess this depends on the actual problem.

**Comment by ppwwyyxx** [comment]
In sync training, the optimizer needs to maintain the global_step by itself, so I shouldn't use a callback to maintain it. That's a problem.

**Comment by PatWie** [comment]
closed in favor of the distributed branch. Nice work @ppwwyyxx !!

**Pull request closed without merging**
