### PR TITLE
start auto deploy to pypip using travis

### PR DESCRIPTION
**Pull request by PatWie**
Next steps:

install ruby to encrypt the pypip -password
--------------
https://gorails.com/setup/ubuntu/16.04:

or copy-paste

    sudo apt-get update
    sudo apt-get install -yy git-core curl zlib1g-dev build-essential libssl-dev libreadline-dev libyaml-dev libsqlite3-dev sqlite3 libxml2-dev libxslt1-dev libcurl4-openssl-dev python-software-properties libffi-dev nodejs

    cd
    git clone https://github.com/rbenv/rbenv.git ~/.rbenv
    echo 'export PATH="$HOME/.rbenv/bin:$PATH"' >> ~/.bashrc
    echo 'eval "$(rbenv init -)"' >> ~/.bashrc
    exec $SHELL

    git clone https://github.com/rbenv/ruby-build.git ~/.rbenv/plugins/ruby-build
    echo 'export PATH="$HOME/.rbenv/plugins/ruby-build/bin:$PATH"' >> ~/.bashrc
    exec $SHELL

    rbenv install 2.4.0
    rbenv global 2.4.0
    ruby -v

    gem install travis # no need for bundler

Test pip locally:
-------------------

        virtualenv --clear -q -p python2.7 venv
        virtualenv venv
        source venv/bin/activate
        cd tensorpack-dir
        python setup.py sdist bdist_egg bdist_wheel
        pip install -e .

Encrypt pypip-password:

        cd tensorpack-dir
        travis encrypt --add deploy.password

This should solve #88 and is based on:
- https://docs.travis-ci.com/user/deployment/pypi/
- http://www.dougalmatthews.com/2016/Sep/01/automate-publishing-to-pypi-with-pbr-and-travis/

which should automatically bump the version number.

But this might have some consequences how to handle the git. Maybe a release branch would be helpful -- or everybody is using an extra branch :wink: before merging to make sure the master branch always pass the tests.

### CODE REVIEW

**Comment by Skylion007** [comment]
As a user of this repo, I really hope that you start having a release branch as I have noticed a lot of almost daily breaking changes when using some the example code. 👍

**Comment by ppwwyyxx** [comment]
Yes I also think it's helpful to have a separate branch for developing. Will look at this when I have more time.

**Comment by ppwwyyxx** [comment]
After a quick look at the whole complicated process I think I'll first trying to write a good setup.py and setup.cfg (with all the settings configured properly, such as requirements) and then look at how to publish on travis.

**Comment by PatWie** [comment]
Then feel free to close this PR when starting from scratch.

**Comment by ppwwyyxx** [comment]
Thanks a lot and I'll refer to the resources you provided!
I've added setup.* which seems to work with `python setup.py install` in a virtualenv. Will test more later.

**Comment by PatWie** [comment]
The current master branch has setup.*, so this can be closed.

**Pull request closed without merging**
