### PR TITLE
fix 207

### PR DESCRIPTION
**Pull request by PatWie**
Test this commit by:
```python
from tensorpack import *


class RepeatedDataPoint(ProxyDataFlow):

    """ Take data points from another DataFlow and produce them a certain number of times
    dp1, ..., dp1, dp2, ..., dp2, ...
    """

    def __init__(self, ds, nr):
        """
        Args:
            ds (DataFlow): input DataFlow
            nr (int): number of times to repeat each datapoint.
        """
        self.nr = nr
        super(RepeatedDataPoint, self).__init__(ds)

    def size(self):
        """
        Raises:
            :class:`ValueError` when nr == -1.
        """
        return self.ds.size() * self.nr

    def get_data(self):
        for dp in self.ds.get_data():
            for _ in range(self.nr):
                print"input is", dp[0].shape
                yield dp


ds = FakeData([(10, 10, 3)], random=False)
ds = RepeatedDataPoint(ds, nr=5)
ds = AugmentImageComponents(ds, [imgaug.RandomCrop((4, 4))], index=[0], copy=False)
ds = PrintData(ds, num=5)

```

gives
```
patwie@pc~/tmp $ python untitled.py  # without copy
input is (10, 10, 3)
input is (4, 4, 3)
input is (4, 4, 3)
input is (4, 4, 3)
input is (4, 4, 3)
[0327 12:25:58 @common.py:655] DataFlow Info:
datapoint 0<5 with 1 components consists of
   dp 0: is ndarray of shape (4, 4, 3) with range [0.0009, 0.9501]
datapoint 1<5 with 1 components consists of
   dp 0: is ndarray of shape (4, 4, 3) with range [0.0009, 0.9501]
datapoint 2<5 with 1 components consists of
   dp 0: is ndarray of shape (4, 4, 3) with range [0.0009, 0.9501]
datapoint 3<5 with 1 components consists of
   dp 0: is ndarray of shape (4, 4, 3) with range [0.0009, 0.9501]
datapoint 4<5 with 1 components consists of
   dp 0: is ndarray of shape (4, 4, 3) with range [0.0009, 0.9501]
patwie@pc~/tmp $ python untitled.py # with copy
input is (10, 10, 3)
input is (10, 10, 3)
input is (10, 10, 3)
input is (10, 10, 3)
input is (10, 10, 3)
[0327 12:26:08 @common.py:655] DataFlow Info:
datapoint 0<5 with 1 components consists of
   dp 0: is ndarray of shape (4, 4, 3) with range [0.0628, 0.9896]
datapoint 1<5 with 1 components consists of
   dp 0: is ndarray of shape (4, 4, 3) with range [0.0628, 0.9896]
datapoint 2<5 with 1 components consists of
   dp 0: is ndarray of shape (4, 4, 3) with range [0.0611, 0.9913]
datapoint 3<5 with 1 components consists of
   dp 0: is ndarray of shape (4, 4, 3) with range [0.0008, 0.9796]
datapoint 4<5 with 1 components consists of
   dp 0: is ndarray of shape (4, 4, 3) with range [0.0131, 0.9913]
```

### CODE REVIEW

**Comment by ppwwyyxx** [comment]
Thanks very much!

**Comment by zxpeter** [comment]
Hi,
How can I get that output?
When I excute that script in terminal it return nothing, when use jupter notebook it return <xxxx obejct>.
I'm using python3.

**Comment by PatWie** [comment]
The `PrintData` has been changed (just have a look at the date).

Something like

```python
from tensorpack import *

seq = FakeData([(10, 10, 3)], random=False)
seq = RepeatedDataPoint(seq, nr=5)
seq = AugmentImageComponents(seq, [imgaug.RandomCrop((4, 4))], index=[0], copy=False)
seq = PrintData(seq)
seq.reset_state()

next(seq.__iter__())

# or just do it yourself

seq.reset_state()
for dp in seq:
  print(dp[0].shape, dp[0].min(), dp[0].max())
```

will work. Not sure, if `PrintData` still supports the `num` parameter. I guess not.

**Comment by zxpeter** [comment]
@PatWie Hi, Thanks for reply and your script works.
@ppwwyyxx Hi, But I find the example in the latest docs shows like below:
> class dataflow.PrintData(ds, num=1, name=None, max_depth=3, max_list=3)[source]
> Bases: tensorpack.dataflow.base.ProxyDataFlow
> Example
> To enable this debugging output, you should place it somewhere in your dataflow like
> 
```
def __iter__():
    ds = SomeDataSource('path/to/lmdb')
    ds = SomeInscrutableMappings(ds)
    ds = PrintData(ds, num=2, max_list=2)
    return ds
ds = __iter__()
```
And it will return 
image

Instead of 
```
[0110 09:22:21 @common.py:589] DataFlow Info:
datapoint 0<2 with 4 components consists of
   0: float with value 0.0816501893251
   1: ndarray:int32 of shape (64,) in range [0, 10]
   2: ndarray:float32 of shape (64, 64) in range [-1.2248, 1.2177]
   3: list of len 50
      0: ndarray:int32 of shape (64, 64) in range [-128, 80]
      1: ndarray:float32 of shape (64, 64) in range [0.8400, 0.6845]
      ...
datapoint 1<2 with 4 components consists of
   0: float with value 5.88252075399
   1: ndarray:int32 of shape (64,) in range [0, 10]
   2: ndarray:float32 of shape (64, 64) with range [-0.9011, 0.8491]
   3: list of len 50
      0: ndarray:int32 of shape (64, 64) in range [-70, 50]
      1: ndarray:float32 of shape (64, 64) in range [0.7400, 0.3545]
      ...
```

**Comment by ppwwyyxx** [comment]
It prints when data is taken from the dataflow.
It does not print anything when you define the dataflow.
Now the docs are updated to clarify this.

See more at https://tensorpack.readthedocs.io/tutorial/dataflow.html

**Pull request merged**
