### PR TITLE
apply chromium formatting

### LINKED ISSUE #698: Add Style guidelines?
I suggest to pick a style for the formatting i.e.
```
[yapf]
based_on_style = chromium
```
```
yapf -i --recursive ./tensorpack
```

### PR DESCRIPTION
**Pull request by Mistobaan**
Fixes #698

### CODE REVIEW

**Comment by ppwwyyxx** [comment]
All sources were checked by flake8. I think that's enough.

**Comment by Mistobaan** [comment]
few questions:
- does flake8 auto-format ?
- do you mind sharing the flake8 configuration in the project ?

**Comment by ppwwyyxx** [comment]
1. It does not.
2. It is in the repo:
```
./tox.ini
./examples/tox.ini
```

**Comment by Mistobaan** [comment]
oh my bad

**Pull request closed without merging**
