### PR TITLE
add VGG19

### PR DESCRIPTION
**Pull request by PatWie**
I would upload the converted (and tested) VGG-19 model as well.

### CODE REVIEW

**Comment by PatWie** [comment]
I did not find a Github gist for the vgg19-deploy.proto of the caffe-model (only train_val).

**Comment by ppwwyyxx** [comment]
Having both load-vgg16 and load-vgg19 still feels weird. Maybe later will move things (with load-alexnet, or maybe load-cpm as well) to a separate directory.

**Comment by PatWie** [comment]
As this is commonly used, I am not sure if we should merge them into a single file hide the model behind flags and if-branches. But a good alternative would be having `VGG16Model` and `VGG19Model`.

**Comment by PatWie** [comment]
Ok too late :grin:

**Comment by ppwwyyxx** [comment]
Ideally similar code should not co-exist, like I'm saying in another PR: https://github.com/ppwwyyxx/tensorpack/pull/481#issuecomment-345672569
And having two models (or just two tower_func) sounds good.
But you're right, for something like VGG, people usually just want something simple to copy and paste..

**Pull request merged**
