### PR TITLE
solution from issue 207

### PR DESCRIPTION
**Pull request by PatWie**
see #207

### CODE REVIEW

**Comment by ppwwyyxx** [comment]
The augmentor now would copy by default. So that issue was fixed

**Comment by PatWie** [comment]
This is not the copy parts. These changes are about the RepeatedDataPoint.

**Comment by ppwwyyxx** [comment]
If no dataflow makes modifications by default, then no dataflow needs to make an explicit copy for potential modification.

**Comment by PatWie** [comment]
Removed the copy-function. But this data-mapping is quite common.

**Pull request merged**
